name: ci

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - uses: actions/checkout@v3

      - name: Run unit tests
        run: | 
          npm i
          npm run test
      
      - name: Generate the code 
        run: npm generate

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Copy files to the s3 website content bucket
        run:
          aws s3 sync dist/ s3://${{ secrets.AWS_S3_BUCKET_NAME }} --acl public-read